function renderAll(){$('kClients').textContent=db.clients.length;$('kProducts').textContent=db.products.length;$('kQuotes').textContent=db.quotes.length;$('kSales').textContent=db.sales.length;renderClients();renderProducts();renderSuppliers();renderQuotes();renderSales()}
function filt(arr,q,fields){q=norm(q);return !q?arr:arr.filter(r=>fields.some(f=>norm(r[f]).includes(q)))}
function renderClients(){const a=filt(db.clients,$('clientFilter').value,['codigo','nome_fantasia','razao_social','cnpj_cpf','cidade']);$('clientTable').innerHTML=a.slice(0,120).map(c=>`<tr><td><b>${esc(c.codigo)}</b></td><td>${esc(c.nome_fantasia)}</td><td>${esc(c.cnpj_cpf)}</td><td>${esc(c.cidade)}/${esc(c.uf)}</td><td>${esc(c.telefone)}</td><td>${esc(c.status)}</td><td class="actions"><button class="icon" onclick="openClient('${c.id}')">Editar</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Nenhum cliente.</td></tr>'}
function renderProducts(){const a=filt(db.products,$('productFilter').value,['codigo','identificacao','descricao','categoria','marca_fabricante']);$('productTable').innerHTML=a.slice(0,150).map(p=>`<tr><td><b>${esc(p.codigo)}</b></td><td>${esc(p.identificacao)}</td><td>${esc(p.descricao)}</td><td>${esc(p.categoria)}</td><td>${esc(p.unidade)}</td><td>${money(p.preco_venda)}</td><td>${esc(p.status)}</td><td><button class="icon" onclick="openProduct('${p.id}')">Editar</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Nenhum produto.</td></tr>'}
function renderSuppliers(){$('supplierTable').innerHTML=db.suppliers.map(s=>`<tr><td><b>${esc(s.codigo)}</b></td><td>${esc(s.nome_fantasia)}</td><td>${esc(s.categoria)}</td><td>${esc(s.telefone)}</td><td>${esc(s.cidade)}/${esc(s.uf)}</td><td>${esc(s.status)}</td><td><button class="icon" onclick="openSupplier('${s.id}')">Editar</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Nenhum fornecedor.</td></tr>'}
function latestRev(q){return (q.orcamento_revisoes||[]).slice().sort((a,b)=>b.numero_revisao-a.numero_revisao)[0]||null}
function quoteStatusLabel(s){return ({RASCUNHO:'Rascunho',EM_NEGOCIACAO:'Em negociação',APROVADO:'Aprovado / Pendente de venda',REPROVADO:'Reprovado',CANCELADO:'Cancelado',CONVERTIDO_EM_VENDA:'Finalizado / Venda gerada'})[s]||s}
function quoteStatusMatches(s,f){if(!f)return true;if(f==='ABERTOS')return ['RASCUNHO','EM_NEGOCIACAO'].includes(s);if(f==='PENDENTES')return s==='APROVADO';if(f==='FINALIZADOS')return s==='CONVERTIDO_EM_VENDA';if(f==='CANCELADOS')return s==='CANCELADO';if(f==='REPROVADOS')return s==='REPROVADO';return true}
function renderQuotes(){let a=db.quotes;const q=norm($('quoteFilter').value),sf=$('quoteStatusFilter').value;if(q)a=a.filter(x=>norm([x.numero,x.clientes?.nome_fantasia].join(' ')).includes(q));a=a.filter(x=>quoteStatusMatches(x.status,sf));$('quoteTable').innerHTML=a.map(o=>{const r=latestRev(o);const canNegotiate=!['CANCELADO','CONVERTIDO_EM_VENDA','REPROVADO'].includes(o.status);const canCancel=!['CANCELADO','CONVERTIDO_EM_VENDA','REPROVADO'].includes(o.status);return `<tr><td><b>${esc(o.numero)}</b></td><td>${esc(o.data_orcamento)}</td><td>${esc(o.clientes?.nome_fantasia)}</td><td>${o.revisao_atual}</td><td>${money(r?.total)}</td><td>${esc(quoteStatusLabel(o.status))}</td><td class="actions"><button class="icon" onclick="openQuote('${o.id}')">Abrir</button>${canNegotiate?`<button class="icon" onclick="openQuote('${o.id}',true)">Negociar</button>`:''}${canCancel?`<button class="icon" onclick="cancelQuote('${o.id}')">Cancelar</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Nenhum orçamento encontrado para esse filtro.</td></tr>'}
function renderSales(){let a=db.sales;const q=norm($('saleFilter').value);if(q)a=a.filter(x=>norm([x.numero,x.orcamentos?.numero,x.clientes?.nome_fantasia].join(' ')).includes(q));$('saleTable').innerHTML=a.map(s=>`<tr><td><b>${esc(s.numero)}</b></td><td>${esc(s.data_venda)}</td><td>${esc(s.orcamentos?.numero)}</td><td>${esc(s.clientes?.nome_fantasia)}</td><td><b>${money(s.valor_total)}</b></td><td><select class="select" onchange="changeSaleStatus('${s.id}',this.value)">${['PEDIDO','EM_ANDAMENTO','FATURADO','CONCLUIDO','CANCELADO'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select></td><td class="actions"><button class="icon" onclick="viewSale('${s.id}')">Ver</button><button class="icon" onclick="deleteSale('${s.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Nenhuma venda ainda.</td></tr>'}
async function changeSaleStatus(id,status){const {error}=await sb.from('vendas').update({status}).eq('id',id);if(error)return alert(error.message);await loadAll()}
async function cancelQuote(id){const o=db.quotes.find(x=>x.id===id);if(!o)return;if(o.status==='CONVERTIDO_EM_VENDA')return alert('Este orçamento já virou venda. Cancele ou exclua a venda antes.');if(o.status==='CANCELADO')return;const motivo=prompt('Motivo do cancelamento do orçamento (opcional):','');if(motivo===null)return;if(!confirm(`Cancelar o orçamento ${o.numero}? O histórico será preservado.`))return;const obs=[o.observacoes||'',motivo?`Cancelamento: ${motivo}`:''].filter(Boolean).join('\n');const {error}=await sb.from('orcamentos').update({status:'CANCELADO',observacoes:obs}).eq('id',id);if(error)return alert(error.message);toast('Orçamento cancelado.');await loadAll();if(quote.id===id)await openQuote(id)}
async function cancelCurrentQuote(){if(quote.id)await cancelQuote(quote.id)}
async function deleteSale(id){const s=db.sales.find(x=>x.id===id);if(!s)return;if(!confirm(`Excluir a venda ${s.numero}?\n\nUse esta opção somente para teste ou lançamento incorreto. A venda e seus itens serão apagados e o orçamento voltará para APROVADO.`))return;const {data,error}=await sb.rpc('excluir_venda_e_reabrir_orcamento',{p_venda_id:id});if(error)return alert(error.message);toast('Venda excluída e orçamento reaberto.');await loadAll()}
