function nextDoc(prefix,list,field='numero'){const y=new Date().getFullYear();let max=0;for(const x of list){const m=String(x[field]||'').match(new RegExp('^'+prefix+'-'+y+'-(\\d+)$'));if(m)max=Math.max(max,+m[1])}return `${prefix}-${y}-${String(max+1).padStart(4,'0')}`}
function newQuote(){quote={id:null,client:null,items:[],revision:0,status:null,latestRevisionId:null};$('quoteTitle').textContent='Novo orçamento';$('qNumber').value=nextDoc('ORC',db.quotes);$('qDate').value=today();$('qValidity').value=15;$('qReason').value='Orçamento inicial';$('qNotes').value='';$('qDiscount').value=0;$('qFreight').value=0;$('clientSearch').value='';$('clientBox').className='clientbox';$('revisionPanel').classList.add('hidden');$('saveQuoteBtn').classList.remove('hidden');$('saveQuoteBtn').textContent='Salvar orçamento';renderQuoteItems()}
function clientSuggestions(q){q=norm(q);const a=q?db.clients.filter(c=>norm([c.codigo,c.nome_fantasia,c.razao_social,c.cnpj_cpf].join(' ')).includes(q)).slice(0,10):[];$('clientSugs').innerHTML=a.map(c=>`<div class="sug" onclick="selectClient('${c.id}')"><b>${esc(c.nome_fantasia)}</b><br><span class="muted">${esc(c.codigo)} • ${esc(c.cnpj_cpf)}</span></div>`).join('');$('clientSugs').classList.toggle('show',a.length>0)}
function selectClient(id){quote.client=db.clients.find(x=>x.id===id);$('clientSugs').classList.remove('show');$('clientSearch').value=`${quote.client.codigo} - ${quote.client.nome_fantasia}`;renderClientBox()}
function renderClientBox(){const c=quote.client;if(!c)return;$('clientBox').className='clientbox show';$('clientBox').innerHTML=`<b>${esc(c.nome_fantasia)}</b> <span class="muted">(${esc(c.codigo)})</span><br><span class="muted">${esc(c.razao_social)} • ${esc(c.cnpj_cpf)} • ${esc(c.cidade)}/${esc(c.uf)} • ${esc(c.telefone)}</span>`}
function productSuggestions(q){q=norm(q);const a=q?db.products.filter(p=>norm([p.codigo,p.identificacao,p.descricao,p.categoria].join(' ')).includes(q)).slice(0,12):[];$('productSugs').innerHTML=a.map(p=>`<div class="sug" onclick="addProduct('${p.id}')"><b>${esc(p.descricao)}</b><br><span class="muted">${esc(p.codigo)} • ${esc(p.unidade)} • ${money(p.preco_venda)}</span></div>`).join('');$('productSugs').classList.toggle('show',a.length>0)}
function addProduct(id){const p=db.products.find(x=>x.id===id);quote.items.push({produto_id:p.id,codigo_produto:p.codigo,descricao:p.descricao,unidade:p.unidade,quantidade:1,preco_unitario:n(p.preco_venda),desconto_percentual:0});$('productSearch').value='';$('productSugs').classList.remove('show');renderQuoteItems()}
function renderQuoteItems(){$('quoteItems').innerHTML=quote.items.map((i,k)=>`<tr><td><b>${esc(i.codigo_produto)}</b></td><td class="desc">${esc(i.descricao)}</td><td>${esc(i.unidade)}</td><td><input type="number" min="0.01" step="0.01" value="${i.quantidade}" onchange="updItem(${k},'quantidade',this.value)"></td><td><input type="number" min="0" step="0.01" value="${i.preco_unitario}" onchange="updItem(${k},'preco_unitario',this.value)"></td><td><input type="number" min="0" max="100" step="0.01" value="${i.desconto_percentual}" onchange="updItem(${k},'desconto_percentual',this.value)"></td><td><b>${money(itemTotal(i))}</b></td><td class="quote-actions"><button class="icon" onclick="removeItem(${k})">×</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Pesquise um produto para adicionar.</td></tr>';calcQuote()}
function itemTotal(i){return n(i.quantidade)*n(i.preco_unitario)*(1-n(i.desconto_percentual)/100)}function updItem(k,f,v){quote.items[k][f]=n(v);renderQuoteItems()}function removeItem(k){quote.items.splice(k,1);renderQuoteItems()}
function calcQuote(){const subtotal=quote.items.reduce((s,i)=>s+itemTotal(i),0),d=Math.min(100,Math.max(0,n($('qDiscount').value))),freight=n($('qFreight').value),total=subtotal*(1-d/100)+freight;$('qSubtotal').textContent=money(subtotal);$('qTotal').textContent=money(total);return{subtotal,total,d,freight}}
function rpcItems(){return quote.items.map(i=>({...i,total_item:itemTotal(i)}))}
async function saveQuote(){if(!quote.client)return toast('Selecione um cliente.');if(!quote.items.length)return toast('Adicione pelo menos um produto.');const c=calcQuote();$('saveQuoteBtn').disabled=true;try{let r;if(!quote.id){r=await sb.rpc('criar_orcamento_com_revisao',{p_numero:$('qNumber').value,p_cliente_id:quote.client.id,p_data_orcamento:$('qDate').value,p_validade_dias:n($('qValidity').value),p_observacoes:$('qNotes').value,p_motivo_revisao:$('qReason').value,p_desconto_geral_percentual:c.d,p_frete_outros:c.freight,p_subtotal:c.subtotal,p_total:c.total,p_itens:rpcItems()});}else{r=await sb.rpc('adicionar_revisao_orcamento',{p_orcamento_id:quote.id,p_motivo_revisao:$('qReason').value||'Negociação / ajuste',p_observacoes:$('qNotes').value,p_validade_dias:n($('qValidity').value),p_desconto_geral_percentual:c.d,p_frete_outros:c.freight,p_subtotal:c.subtotal,p_total:c.total,p_itens:rpcItems()})}if(r.error)throw r.error;toast(quote.id?'Nova revisão salva.':'Orçamento criado.');await loadAll();await openQuote(quote.id||r.data)}catch(e){alert(e.message||e)}finally{$('saveQuoteBtn').disabled=false}}
async function openQuote(id,neg=false){const o=db.quotes.find(x=>x.id===id);if(!o)return;const rr=await sb.from('orcamento_revisoes').select('*, orcamento_itens(*)').eq('orcamento_id',id).order('numero_revisao',{ascending:false});if(rr.error)return alert(rr.error.message);const latest=rr.data[0];quote={id:o.id,client:db.clients.find(c=>c.id===o.cliente_id)||null,items:(latest?.orcamento_itens||[]).map(i=>({produto_id:i.produto_id,codigo_produto:i.codigo_produto,descricao:i.descricao,unidade:i.unidade,quantidade:n(i.quantidade),preco_unitario:n(i.preco_unitario),desconto_percentual:n(i.desconto_percentual)})),revision:o.revisao_atual,status:o.status,latestRevisionId:latest?.id,revisions:rr.data};$('quoteTitle').textContent=`${o.numero} • Revisão ${o.revisao_atual}`;$('qNumber').value=o.numero;$('qDate').value=o.data_orcamento;$('qValidity').value=o.validade_dias;$('qReason').value=neg?'Negociação / ajuste':'';$('qNotes').value=latest?.observacoes||o.observacoes||'';$('qDiscount').value=n(latest?.desconto_geral_percentual);$('qFreight').value=n(latest?.frete_outros);$('clientSearch').value=quote.client?`${quote.client.codigo} - ${quote.client.nome_fantasia}`:'';renderClientBox();renderQuoteItems();$('revisionPanel').classList.remove('hidden');renderRevisionHistory();const locked=['CANCELADO','CONVERTIDO_EM_VENDA','REPROVADO'].includes(o.status);$('saveQuoteBtn').textContent='Salvar nova revisão';$('saveQuoteBtn').classList.toggle('hidden',locked);$('cancelQuoteBtn').classList.toggle('hidden',locked);$('approveBtn').classList.toggle('hidden',locked);if(o.status==='APROVADO'){$('approveBtn').textContent='Converter em venda';$('approveBtn').onclick=convertCurrentQuote}else{$('approveBtn').textContent='Aprovar orçamento';$('approveBtn').onclick=approveCurrentQuote}if(o.status==='CANCELADO')toast('Orçamento cancelado: somente consulta.');if(o.status==='CONVERTIDO_EM_VENDA')toast('Orçamento finalizado: venda já gerada.');go('quote')}
function renderRevisionHistory(){$('revisionHistory').innerHTML=(quote.revisions||[]).map(r=>`<div class="hist"><div><b>Revisão ${r.numero_revisao}</b> <span class="pill">${money(r.total)}</span><br><span class="muted">${esc(r.motivo_revisao||'')} • ${new Date(r.created_at).toLocaleString('pt-BR')}</span></div><button class="icon" onclick="loadRevision('${r.id}')">Visualizar</button></div>`).join('')}
async function loadRevision(id){const r=(quote.revisions||[]).find(x=>x.id===id);if(!r)return;quote.items=(r.orcamento_itens||[]).map(i=>({produto_id:i.produto_id,codigo_produto:i.codigo_produto,descricao:i.descricao,unidade:i.unidade,quantidade:n(i.quantidade),preco_unitario:n(i.preco_unitario),desconto_percentual:n(i.desconto_percentual)}));$('qDiscount').value=n(r.desconto_geral_percentual);$('qFreight').value=n(r.frete_outros);$('qNotes').value=r.observacoes||'';$('qReason').value='Nova negociação baseada na revisão '+r.numero_revisao;renderQuoteItems();toast('Revisão carregada como base para uma nova negociação.')}
async function approveCurrentQuote(){if(!quote.id)return;const {error}=await sb.from('orcamentos').update({status:'APROVADO'}).eq('id',quote.id);if(error)return alert(error.message);toast('Orçamento aprovado. Agora pode virar venda.');await loadAll();await openQuote(quote.id)}
async function convertCurrentQuote(){if(!quote.id||!quote.latestRevisionId)return;const saleNo=nextDoc('VEN',db.sales);if(!confirm(`Converter ${$('qNumber').value} em venda ${saleNo}?`))return;const r=await sb.rpc('converter_orcamento_em_venda',{p_orcamento_id:quote.id,p_revisao_id:quote.latestRevisionId,p_numero_venda:saleNo,p_observacoes:$('qNotes').value});if(r.error)return alert(r.error.message);toast('Venda criada com sucesso!');await loadAll();go('sales')}
async function viewSale(id){const s=db.sales.find(x=>x.id===id);const r=await sb.from('venda_itens').select('*').eq('venda_id',id);if(r.error)return alert(r.error.message);openModal('Venda '+s.numero,`<div class="notice ok">Originada do orçamento <b>${esc(s.orcamentos?.numero)}</b>. Valor total: <b>${money(s.valor_total)}</b></div><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>Produto</th><th>Descrição</th><th>Qtd</th><th>Preço</th><th>Total</th></tr></thead><tbody>${(r.data||[]).map(i=>`<tr><td>${esc(i.codigo_produto)}</td><td>${esc(i.descricao)}</td><td>${i.quantidade}</td><td>${money(i.preco_unitario)}</td><td>${money(i.total_item)}</td></tr>`).join('')}</tbody></table></div>`) }
function openModal(t,b){$('modalTitle').textContent=t;$('modalBody').innerHTML=b;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}
function nextCode(prefix,arr){let m=0;for(const x of arr){const z=String(x.codigo||'').match(/(\d+)$/);if(z)m=Math.max(m,+z[1])}return prefix+String(m+1).padStart(prefix==='PRD'?5:4,'0')}
