function injectCiclo1Ui(){
  const nav=document.querySelector('.nav');
  const productsBtn=nav?.querySelector('[data-page="products"]');
  const suppliersBtn=nav?.querySelector('[data-page="suppliers"]');
  if(nav&&productsBtn&&suppliersBtn&&!$('cadastrosSub')){
    const group=document.createElement('div');group.className='nav-group';group.innerHTML=`<div class="nav-group-label" onclick="toggleCadastros()">▣ <span>Cadastros</span><b id="cadastrosChevron">⌃</b></div><div id="cadastrosSub" class="nav-sub open"><button data-page="suppliers">⚙ <span>Fornecedor</span></button><button data-page="products">▦ <span>Produto</span></button><button data-page="categories">◫ <span>Categoria & Segmento</span></button></div>`;
    productsBtn.replaceWith(group);suppliersBtn.remove();
  }
  const adminNav=$('adminNav');if(nav&&adminNav&&!nav.querySelector('[data-page="mdvdata"]')){const b=document.createElement('button');b.dataset.page='mdvdata';b.innerHTML='🏢 <span>Dados MDV</span>';nav.insertBefore(b,adminNav)}
  const supplierPage=$('suppliers');if(supplierPage&&!$('supplierFilter'))supplierPage.innerHTML=`<div class="card"><div class="section"><h3>Fornecedores</h3><button class="btn primary" onclick="openSupplier()">+ Novo fornecedor</button></div><div class="toolbar supplier-toolbar"><input id="supplierFilter" class="input" placeholder="Pesquisar código, nome, CNPJ, categoria..." oninput="renderSuppliers()"><div id="supplierStatusToggle" class="segmented"><button class="active" data-status="ATIVO" onclick="setSupplierStatus('ATIVO')">Ativos</button><button data-status="INATIVO" onclick="setSupplierStatus('INATIVO')">Inativos</button></div></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Nome</th><th>Categoria</th><th>Telefone</th><th>Cidade/UF</th><th>Status</th><th>Ações</th></tr></thead><tbody id="supplierTable"></tbody></table></div></div>`;
  const productPage=$('products');if(productPage)productPage.innerHTML=`<div class="card"><div class="section"><h3>Produtos</h3><button class="btn primary" onclick="openProduct()">+ Novo produto</button></div><div class="toolbar"><input id="productFilter" class="input" placeholder="Pesquisar código, TAG, descrição, categoria..." style="max-width:700px" oninput="renderProducts()"></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>TAG Produto</th><th>TAG Cliente</th><th>Descrição</th><th>Categoria</th><th>Segmento</th><th>UN</th><th>Preço venda</th><th>Status</th><th>Ações</th></tr></thead><tbody id="productTable"></tbody></table></div></div>`;
  const main=document.querySelector('.main');if(main&&!$('categories')){const s=document.createElement('section');s.className='page';s.id='categories';s.innerHTML=`<div class="card"><div class="section"><div><h3>Categoria & Segmento</h3><p class="muted">Cadastre as opções usadas nos produtos.</p></div><button class="btn primary" onclick="openCategory()">+ Novo</button></div><div class="toolbar"><input id="categoryFilter" class="input" placeholder="Pesquisar categoria ou segmento..." style="max-width:600px" oninput="renderCategories()"></div><div class="table-wrap"><table><thead><tr><th>Categoria</th><th>Segmento</th><th>Status</th><th>Ações</th></tr></thead><tbody id="categoryTable"></tbody></table></div></div>`;main.appendChild(s)}
  if(main&&!$('mdvdata')){const s=document.createElement('section');s.className='page';s.id='mdvdata';s.innerHTML=`<div class="grid2 mdv-grid"><div class="card"><div class="section"><div><h3>Razões sociais e CNPJs</h3><p class="muted">Empresas disponíveis para propostas e emissão de NF.</p></div><button class="btn primary" onclick="openMdvCnpj()">+ Novo CNPJ</button></div><div class="toolbar"><input id="mdvCnpjFilter" class="input" placeholder="Pesquisar razão social ou CNPJ..." oninput="renderMdvData()"></div><div class="table-wrap"><table><thead><tr><th>Razão Social</th><th>Nome Fantasia</th><th>CNPJ</th><th>Status</th><th>Ações</th></tr></thead><tbody id="mdvCnpjTable"></tbody></table></div></div><div class="card"><h3 style="margin-top:0">Logo da MDV</h3><p class="muted">A imagem será usada como identidade visual do sistema.</p><div id="mdvLogoPreview" class="logo-preview"></div><input id="mdvLogoInput" class="input" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"><button class="btn primary" style="margin-top:10px" onclick="uploadMdvLogo()">Atualizar logo</button><p class="muted" style="font-size:12px">PNG, JPG, WEBP ou SVG • máximo 5 MB.</p></div></div>`;main.appendChild(s)}
  const style=document.createElement('style');style.textContent=`.nav-group{display:grid;gap:4px}.nav-group-label{padding:12px 14px;border-radius:12px;color:#dbe7f1;display:flex;gap:10px;align-items:center;cursor:pointer}.nav-group-label:hover{background:rgba(255,255,255,.12);color:#fff}.nav-group-label b{margin-left:auto}.nav-sub{display:none;gap:4px;padding-left:10px}.nav-sub.open{display:grid}.nav-sub button{padding-left:24px!important}.supplier-toolbar{align-items:center}.supplier-toolbar>.input{max-width:620px;flex:1}.segmented{display:inline-flex;background:#edf2f7;border-radius:11px;padding:3px;gap:3px}.segmented button{border:0;background:transparent;padding:8px 13px;border-radius:8px;font-weight:700;color:#64748b}.segmented button.active{background:#fff;color:#143a5e;box-shadow:0 2px 8px rgba(20,49,78,.12)}.logo.has-image{background:#fff;overflow:hidden}.logo.has-image img{width:100%;height:100%;object-fit:contain}.logo-preview{height:150px;border:1px dashed #cbd5e1;border-radius:14px;display:grid;place-items:center;margin:16px 0;background:#f8fafc}.logo-preview img{max-width:90%;max-height:120px;object-fit:contain}.logo-placeholder{width:80px;height:80px;border-radius:18px;background:#d8ae55;display:grid;place-items:center;font-weight:900;color:#183653}.mdv-grid{grid-template-columns:1.5fr .5fr}@media(max-width:1050px){.nav-group-label span{display:none}.nav-sub{padding-left:0}.nav-sub button{padding-left:14px!important}.mdv-grid{grid-template-columns:1fr}}@media(max-width:700px){.mdv-grid{grid-template-columns:1fr}}`;document.head.appendChild(style)
}
function toggleCadastros(){const sub=$('cadastrosSub');if(!sub)return;sub.classList.toggle('open');if($('cadastrosChevron'))$('cadastrosChevron').textContent=sub.classList.contains('open')?'⌃':'⌄'}
async function loadExtraData(){const [cat,cnpj,cfg]=await Promise.all([sb.from('categorias_segmentos').select('*').order('categoria').order('segmento'),sb.from('cnpjs_mdv').select('*').order('razao_social'),sb.from('dados_mdv_config').select('*').eq('id',1).maybeSingle()]);if(cat.error||cnpj.error||cfg.error)console.error('Cadastros auxiliares:',cat.error,cnpj.error,cfg.error);if(!cat.error)db.categories=cat.data||[];if(!cnpj.error)db.mdvCnpjs=cnpj.data||[];if(!cfg.error)db.mdvConfig=cfg.data||null;renderCategories();renderMdvData();renderProducts();renderSuppliers();applyMdvLogo()}
function initCiclo1(){injectCiclo1Ui();db.categories=[];db.mdvCnpjs=[];db.mdvConfig=null;titles.categories=['Categoria & Segmento','Cadastros usados para classificar os produtos.'];titles.mdvdata=['Dados MDV','Razões sociais, CNPJs e identidade da empresa.'];const coreGo=go;go=function(id){coreGo(id);if(['products','suppliers','categories'].includes(id))$('cadastrosSub')?.classList.add('open')};renderSuppliers=renderSuppliersEnhanced;renderProducts=renderProductsEnhanced;openProduct=openProductEnhanced;const coreLoadAll=loadAll;loadAll=async function(){await coreLoadAll();await loadExtraData()};document.querySelectorAll('.nav button[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));if(appStarted)loadExtraData()}
initCiclo1();
(()=>{const s=document.createElement('script');s.src='app9.js?v=20260904c2';s.onerror=()=>console.error('Falha ao carregar app9.js');document.body.appendChild(s)})();
