// Ciclo 2 - somente ajustes solicitados em Clientes e Fornecedores
let clientStatusMode='ATIVO';
function setClientStatus(status){clientStatusMode=status;document.querySelectorAll('#clientStatusToggle button').forEach(b=>b.classList.toggle('active',b.dataset.status===status));renderClients()}
function renderClientsCycle2(){const q=norm($('clientFilter')?.value||'');let a=(db.clients||[]).filter(c=>String(c.status||'ATIVO').toUpperCase()===clientStatusMode);if(q)a=a.filter(c=>norm([c.codigo,c.nome_fantasia,c.razao_social,c.cnpj_cpf,c.telefone,c.email,c.cidade,c.uf].join(' ')).includes(q));$('clientTable').innerHTML=a.slice(0,200).map(c=>`<tr><td><b>${esc(c.codigo)}</b></td><td>${esc(c.nome_fantasia)}</td><td>${esc(c.cnpj_cpf)}</td><td>${esc(c.cidade)}/${esc(c.uf)}</td><td>${esc(c.telefone)}</td><td>${esc(c.status)}</td><td class="actions"><button class="icon" onclick="openClient('${c.id}')">Editar</button></td></tr>`).join('')||`<tr><td colspan="7" class="empty">Nenhum cliente ${clientStatusMode==='ATIVO'?'ativo':'inativo'} encontrado.</td></tr>`}
function openSupplierCycle2(id=''){const s=(db.suppliers||[]).find(x=>x.id===id)||{};openModal(id?'Editar fornecedor':'Novo fornecedor',`<form id="fSupplier" class="form-grid"><div><label>Código</label><input name="codigo" class="input" value="${esc(s.codigo||nextCode('FOR',db.suppliers||[]))}" readonly></div><div class="span2"><label>Nome fantasia *</label><input name="nome_fantasia" class="input" value="${esc(s.nome_fantasia||'')}" required></div><div><label>Status</label><select name="status" class="select"><option ${s.status!=='INATIVO'?'selected':''}>ATIVO</option><option ${s.status==='INATIVO'?'selected':''}>INATIVO</option></select></div><div class="span2"><label>Razão social</label><input name="razao_social" class="input" value="${esc(s.razao_social||'')}"></div><div><label>CNPJ/CPF</label><input name="cnpj_cpf" class="input" value="${esc(s.cnpj_cpf||'')}"></div><div><label>Contato</label><input name="contato" class="input" value="${esc(s.contato||'')}"></div><div><label>Telefone</label><input name="telefone" class="input" value="${esc(s.telefone||'')}"></div><div><label>E-mail</label><input name="email" class="input" value="${esc(s.email||'')}"></div><div><label>Categoria</label><select name="categoria" class="select">${catOpts(s.categoria||'')}</select></div><div><label>Cidade</label><input name="cidade" class="input" value="${esc(s.cidade||'')}"></div><div><label>UF</label><input name="uf" class="input" value="${esc(s.uf||'')}"></div><div class="span4" style="text-align:right"><button type="button" class="btn ghost" onclick="closeModal()">Cancelar</button> <button class="btn primary">Salvar</button></div></form>`);$('fSupplier').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));const r=id?await sb.from('fornecedores').update(v).eq('id',id):await sb.from('fornecedores').insert(v);if(r.error)return alert(r.error.message);closeModal();await loadAll();toast('Fornecedor salvo.')}}
function injectCiclo2Ui(){
  const nav=document.querySelector('.nav'),sub=$('cadastrosSub'),clientTop=nav?.querySelector(':scope > button[data-page="clients"]');
  if(sub&&!sub.querySelector('[data-page="clients"]')){const b=document.createElement('button');b.dataset.page='clients';b.innerHTML='👤 <span>Cliente</span>';b.onclick=()=>go('clients');sub.prepend(b)}
  if(clientTop)clientTop.remove();
  const clientPage=$('clients');if(clientPage)clientPage.innerHTML=`<div class="card"><div class="section"><h3>Clientes</h3><button class="btn primary" onclick="openClient()">+ Novo cliente</button></div><div class="toolbar supplier-toolbar"><input id="clientFilter" class="input" placeholder="Pesquisar código, nome, CNPJ/CPF, cidade..." oninput="renderClients()"><div id="clientStatusToggle" class="segmented"><button class="active" data-status="ATIVO" onclick="setClientStatus('ATIVO')">Ativos</button><button data-status="INATIVO" onclick="setClientStatus('INATIVO')">Inativos</button></div></div><div class="table-wrap"><table><thead><tr><th>Código</th><th>Nome</th><th>CNPJ/CPF</th><th>Cidade/UF</th><th>Telefone</th><th>Status</th><th>Ações</th></tr></thead><tbody id="clientTable"></tbody></table></div></div>`;
}
function initCiclo2(){injectCiclo2Ui();renderClients=renderClientsCycle2;openSupplier=openSupplierCycle2;const prevGo=go;go=function(id){prevGo(id);if(id==='clients')$('cadastrosSub')?.classList.add('open')};document.querySelectorAll('#cadastrosSub button[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));renderClients();}
initCiclo2();
